// Custom strategies: one file each in cpp/strategies/custom/, registered by
// name with no other file to edit.
//
// A file NAME.cpp defines a class NAME derived from xau::Strategy, with a
// constructor taking the lot size, and ends with
//
//     XAU_CUSTOM_STRATEGY(NAME, H1, "one line on what it trades and why")
//
// at global scope. The build lists every file in the folder and calls each
// one's registration explicitly. Self-registering statics are not used: a
// static library drops object files nothing references, and registrations
// living in them vanish silently from the MT5 DLL -- the one place a missing
// strategy matters most.
//
// Once built, the strategy is everywhere a registry name is: the lab, the
// terminal, validate, and the MT5 bridge (InpStrategy = NAME).
// docs/CUSTOM-STRATEGIES.md has the rules and a prompt for writing one.
#pragma once

#include "xau/bar.hpp"
#include "xau/strategy.hpp"

#include <functional>
#include <memory>

namespace xau {

class CustomRegistrar {
public:
    virtual ~CustomRegistrar() = default;
    // Which file the next add() comes from, and the SHA-256 of its text: an
    // edited strategy is a new trial, and the lab counts it as one.
    virtual void begin_source(const char* file, const char* sha256) = 0;
    virtual void add(const char* name, const char* description, Timeframe tf,
                     std::function<std::unique_ptr<Strategy>(double lots)> make) = 0;
};

// Generated by the build from the files in cpp/strategies/custom/.
void register_custom_strategies(CustomRegistrar& r);

}  // namespace xau

#define XAU_CUSTOM_STRATEGY(CLASS, TF, DESCRIPTION)                                      \
    void xau_custom_register_##CLASS(::xau::CustomRegistrar& r);                         \
    void xau_custom_register_##CLASS(::xau::CustomRegistrar& r) {                        \
        r.add(#CLASS, DESCRIPTION, ::xau::Timeframe::TF,                                 \
              [](double lots) -> std::unique_ptr<::xau::Strategy> {                      \
                  return std::make_unique<CLASS>(lots);                                  \
              });                                                                        \
    }
