cmake_minimum_required(VERSION 3.25)   # script mode starts with no policies set
# Writes the registration list for cpp/strategies/custom/. Run by the build
# whenever a file there is added, removed or edited.
#   -DOUT=<generated .cpp>  -DSOURCES=<files, separated by |>
string(REPLACE "|" ";" SOURCES "${SOURCES}")
set(decls "")
set(calls "")
set(seen "")
foreach(f IN LISTS SOURCES)
    if(f STREQUAL "")
        continue()
    endif()
    get_filename_component(name "${f}" NAME_WE)
    if(NOT name MATCHES "^[A-Za-z][A-Za-z0-9_]*$")
        message(FATAL_ERROR "custom strategy '${f}': the file name is the class name and "
                            "must be a C++ identifier (letters, digits, underscores)")
    endif()
    string(TOLOWER "${name}" lname)
    if(lname IN_LIST seen)
        message(FATAL_ERROR "custom strategy '${name}': two files differ only in case")
    endif()
    list(APPEND seen "${lname}")
    file(SHA256 "${f}" sha)
    string(APPEND decls "void xau_custom_register_${name}(::xau::CustomRegistrar& r);\n")
    string(APPEND calls "    r.begin_source(\"${name}.cpp\", \"${sha}\");\n")
    string(APPEND calls "    xau_custom_register_${name}(r);\n")
endforeach()
file(WRITE "${OUT}"
"// GENERATED by cpp/core/gen_custom.cmake from cpp/strategies/custom/. Do not edit.
#include \"xau/custom.hpp\"

${decls}
namespace xau {
void register_custom_strategies(CustomRegistrar& r) {
    (void)r;
${calls}}
}  // namespace xau
")
